branch-defaults:
  master:
    environment: wedsite-prod
    group_suffix: null
environment-defaults:
  wedsite-prod:
    branch: null
    repository: null
global:
  application_name: wedsite-prod
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
