branch-defaults:
  master:
    environment: wedsite-dev
global:
  application_name: wedsite
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
