# Generated by Django 2.2.1 on 2019-06-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('is_attending', models.NullBooleanField(default=None)),
                ('is_attending_luncheon', models.NullBooleanField(default=None)),
                ('dietary_restrictions', models.CharField(blank=True, choices=[('V', 'Vegetarian'), ('VG', 'Vegan'), ('GF', 'Gluten free'), ('DF', 'Dairy free'), ('K', 'Kosher'), ('H', 'Halal'), ('A', 'Allergy'), ('O', 'Other')], max_length=20, null=True)),
                ('child_meal', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Party')),
            ],
        ),
    ]
