# Generated by Django 2.2.1 on 2019-06-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='dietary_restriction_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='guest',
            name='dietary_restrictions',
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='dietary_restrictions',
            field=models.ManyToManyField(to='guests.DietaryRestriction'),
        ),
    ]
